name: phonepe_pg
description: This package provides a Flutter wrapper for the PhonePe PG SDK, allowing you to easily accept payments from your Flutter Web app.
version: 0.0.1
homepage: https://github.com/paraggupta9065/phonepe_pg

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: 3.0.3
  http: 0.13.0
  url_launcher: 6.1.14
  uuid: 4.1.0
  webview_flutter_web: 0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

